/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IPhArrowLeftDuotone: typeof import('~icons/ph/arrow-left-duotone')['default']
    IPhGithubLogoDuotone: typeof import('~icons/ph/github-logo-duotone')['default']
    IPhHeartStraightDuotone: typeof import('~icons/ph/heart-straight-duotone')['default']
    IPhHouseDuotone: typeof import('~icons/ph/house-duotone')['default']
    IPhMoonStarsDuotone: typeof import('~icons/ph/moon-stars-duotone')['default']
    IPhSunDuotone: typeof import('~icons/ph/sun-duotone')['default']
    IPhTranslateDuotone: typeof import('~icons/ph/translate-duotone')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
